=== tongdangquang/Tich_hop_he_thong_PM_HaUI/TX1/de5/src/de5/ChamCong.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
           
    <!--ràng buộc mã nhân viên-->
    <xs:simpleType name="manv_type">
        <xs:restriction base="xs:ID">
            <xs:length value="5"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!--ràng buộc cho ca làm-->
    <xs:simpleType name="calamviec_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="C1"/> 
            <xs:enumeration value="C2"/> 
            <xs:enumeration value="C3"/> 
        </xs:restriction>
    </xs:simpleType>
    
    <!--ràng buộc nhân viên-->
    <xs:complexType name="nhanvien_type">
        <xs:sequence>
            <xs:element name="CaLamViec" type="calamviec_type"/>
            <xs:element name="GioVao" type="xs:string"/>
            <xs:element name="GioRa" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="MaNV" type="manv_type" use="required"/>
    </xs:complexType>
    
    <!--ràng buộc cho ngày làm việc-->
    <xs:complexType name="ngaylamviec_type">
        <xs:sequence>
            <xs:element name="NhanVien" type="nhanvien_type" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="Ngay" type="xs:date" use="required"/>
    </xs:complexType>
    
    <!--ràng buộc cho chấm công-->
    <xs:complexType name="chamcong_type">
        <xs:sequence>
            <xs:element name="NgayLamViec" type="ngaylamviec_type" maxOccurs="31"/>
        </xs:sequence>
        <xs:attribute name="BoPhan" type="xs:string" use="required"/>
    </xs:complexType>
    
    <!--phần tử gốc-->
    <xs:element name="ChamCong" type="chamcong_type" />
</xs:schema>

=== tongdangquang/Tich_hop_he_thong_PM_HaUI/TX1/de5/src/de5/ChamCong.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="ChamCong.xsl"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<ChamCong
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='ChamCong.xsd'
    BoPhan="Sản xuất">
    <NgayLamViec Ngay="2022-11-18">
        <NhanVien MaNV="S0001">
            <CaLamViec>C1</CaLamViec>
            <GioVao>05:50</GioVao>
            <GioRa>15:00</GioRa>
        </NhanVien>
        <NhanVien MaNV="S0002">
            <CaLamViec>C2</CaLamViec>
            <GioVao>08:00</GioVao>
            <GioRa>16:00</GioRa>
        </NhanVien>
        <NhanVien MaNV="S0003">
            <CaLamViec>C3</CaLamViec>
            <GioVao>17:00</GioVao>
            <GioRa>22:00</GioRa>
        </NhanVien>
    </NgayLamViec>
    
    <NgayLamViec Ngay="2022-11-19">
        <NhanVien MaNV="S0004">
            <CaLamViec>C1</CaLamViec>
            <GioVao>07:00</GioVao>
            <GioRa>12:00</GioRa>
        </NhanVien>
        <NhanVien MaNV="S0005">
            <CaLamViec>C2</CaLamViec>
            <GioVao>12:00</GioVao>
            <GioRa>18:00</GioRa>
        </NhanVien>
        <NhanVien MaNV="S0006">
            <CaLamViec>C3</CaLamViec>
            <GioVao>18:00</GioVao>
            <GioRa>23:59</GioRa>
        </NhanVien>
    </NgayLamViec>
</ChamCong>
